#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
[ -f /etc/conf.d/axum.conf ] && . /etc/conf.d/axum.conf

PID=`pidof -o %PPID /usr/bin/axum-address`
case "$1" in
  start)
    stat_busy "Starting Axum Address Server"
    [ -z "$PID" ] && /usr/bin/axum-address -i $(axum_id address) ${AXUMADDRARGS}
    if [ $? -gt 0 ]; then
      stat_fail
    else
      echo $PID > /var/run/axum-address.pid
      add_daemon axum-address
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Axum Address Server"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm -f /var/run/axum-address.pid
      rm_daemon axum-address
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
