#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
[ -f /etc/conf.d/axum-rack.conf ] && . /etc/conf.d/axum-rack.conf

case "$1" in
  start)
    stat_busy "Cleaning recent_changes table in database"
    psql axum axum -q -c "TRUNCATE TABLE recent_changes"
    if [ $? -gt 0 ]; then
      stat_fail
    else
      stat_done
    fi
    ;;
  stop)
    stat_done
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
