#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
[ -f /etc/conf.d/axum-rack.conf ] && . /etc/conf.d/axum-rack.conf

PID=`pidof -o %PPID /usr/bin/axum-gateway`
OEMName=`cat /var/lib/axum/OEMFullProductName`
case "$1" in
  start)
    stat_busy "Starting $OEMName Gateway"
    CAN_INTERFACE='/dev/ttyS1'
    if (ifconfig can0 >/dev/null 2>&1); then
      CAN_INTERFACE='can0'
    fi
    [ -z "$PID" ] && /usr/bin/axum-gateway -i $(axum_id gateway) -c ${CAN_INTERFACE} ${AXUMGATEWAYARGS}
    if [ $? -gt 0 ]; then
      stat_fail
    else
      echo $PID > /var/run/axum-gateway.pid
      add_daemon axum-gateway
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping $OEMName Gateway"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm -f /var/run/axum-gateway.pid
      rm_daemon axum-gateway
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
