#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
[ -f /etc/conf.d/axum-rack.conf ] && . /etc/conf.d/axum-rack.conf

case "$1" in
  start)
    stat_busy "Remove the old postmaster.pid file"
    rm -f /var/lib/postgres/data/postmaster.pid
    stat_done
    ;;
  stop)
    stat_done
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
